import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Reads other-readings.tsv: glyph -> its standard readings besides the main
 * one. Generated by scripts/build-other-readings.mjs; see there for sources.
 */
export function loadOtherReadings(): Map<string, string[]> {
  const readings = new Map<string, string[]>();
  for (const line of readFileSync(
    join(process.cwd(), "src/server/database/seed/other-readings.tsv"),
    "utf-8",
  ).split("\n")) {
    if (!line.trim() || line.startsWith("#")) continue;
    const [glyph, list = ""] = line.split("\t");
    readings.set(glyph!, list.split(",").filter(Boolean));
  }
  return readings;
}
